services:
  server:
    image: jrerest:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jrerest.rule=Host(`rigo.cc`)"
      - "traefik.http.routers.jrerest.entrypoints=websecure"
      - "traefik.http.routers.jrerest.tls.certresolver=myresolver"
    deploy: 
      mode: replicated
      replicas: 3
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=rigo@rigo.cc"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt

