services:
  server:
    image: jrerest:latest
    container_name: jrerest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jrerest.rule=Host(`rigo.cc`)"
      - "traefik.http.routers.jrerest.entrypoints=websecure"
      - "traefik.http.routers.jrerest.certsresolver=myresolver"
    deploy: 
      mode: replicated
      replicas: 3
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificateresolvers.myresolver.acme.tlschallenge=true"
      - "--certificateresolvers.myresolver.acme.email=rigo@rigo.cc"
      - "--certificateresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  letsencrypt:
